# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Research_code',
                'doc_host': 'https://gbeane66.github.io',
                'git_url': 'https://github.com/gbeane66/Research_code',
                'lib_path': 'Research_code'},
  'syms': {'Research_code.core': {'Research_code.core.foo': ('core.html#foo', 'Research_code/core.py')}}}
